-- 1. CREATE TABLE
CREATE OR REPLACE TABLE CORE.GROUP_PREFERENCES (
    GROUP_ID STRING,
    USER_ID INT AUTOINCREMENT,
    BUDGET FLOAT,
    DESTINATION STRING,
    DURATION INT,
    TRAVEL_STYLE STRING,
    SHOPPING_INTEREST STRING,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- 2. CREATE VIEW FOR ANALYTICS (LOWERCASE SAFE)
CREATE OR REPLACE VIEW CORE.GROUP_ANALYTICS AS
SELECT
    GROUP_ID AS "group_id",
    COUNT(*) AS "total_users",
    AVG(BUDGET) AS "avg_budget",
    MIN(BUDGET) AS "min_budget",
    MAX(BUDGET) AS "max_budget",
    MAX(DURATION) AS "max_duration",
    MIN(DURATION) AS "min_duration"
FROM CORE.GROUP_PREFERENCES
GROUP BY GROUP_ID;

-- 3. QUERY THE VIEW
SELECT *
FROM CORE.GROUP_ANALYTICS;

-- 4. CREATE STORED PROCEDURE
CREATE OR REPLACE PROCEDURE CORE.CLEAR_GROUP(GID STRING)
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    DELETE FROM CORE.GROUP_PREFERENCES
    WHERE GROUP_ID = :GID;
    RETURN 'Group Cleared Successfully';
END;
$$;

-- 5. CALL PROCEDURE TO CLEAR GROUP
CALL CORE.CLEAR_GROUP('G1');

-- 6. INSERT TEST DATA
INSERT INTO CORE.GROUP_PREFERENCES (
    GROUP_ID,
    BUDGET,
    DESTINATION,
    DURATION,
    TRAVEL_STYLE,
    SHOPPING_INTEREST
)
VALUES
    ('G1', 50000, 'Goa', 3, 'Relaxed', 'Medium'),
    ('G1', 60000, 'Goa', 4, 'Adventure', 'High');

-- 7. QUERY TABLE
SELECT *
FROM CORE.GROUP_PREFERENCES;

-- 8. QUERY ANALYTICS VIEW
SELECT *
FROM CORE.GROUP_ANALYTICS;

-- 9. CLEAR THE GROUP
CALL CORE.CLEAR_GROUP('G1');

-- 10. VERIFY DATA CLEARED
SELECT *
FROM CORE.GROUP_PREFERENCES;

-- BULK LOADING SETUP

-- 11. CREATE FILE FORMAT FOR CSV
CREATE OR REPLACE FILE FORMAT CORE.CSV_FORMAT
TYPE = 'CSV'
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
SKIP_HEADER = 1;

-- 12. CREATE STAGE FOR FILE UPLOAD
CREATE OR REPLACE STAGE CORE.PACKVOTE_STAGE
FILE_FORMAT = CORE.CSV_FORMAT;

-- 13. COPY INTO - BULK LOAD DATA FROM STAGE
COPY INTO CORE.GROUP_PREFERENCES
FROM @CORE.PACKVOTE_STAGE
FILE_FORMAT = (FORMAT_NAME = CORE.CSV_FORMAT)
ON_ERROR = 'SKIP_FILE';

-- VERIFICATION COMMANDS (Run separately after bulk loading)

-- 14. CHECK STAGE CONTENTS
LIST @CORE.PACKVOTE_STAGE;

-- 15. SHOW STAGES
SHOW STAGES;

-- 16. SHOW FILE FORMATS
SHOW FILE FORMATS;

-- 17. DESCRIBE TABLE STRUCTURE
DESC TABLE CORE.GROUP_PREFERENCES;

-- 18. DESCRIBE STAGE
DESC STAGE CORE.PACKVOTE_STAGE;

-- 19. VERIFY DATA LOADED (Run this AFTER bulk loading)
SELECT *
FROM CORE.GROUP_PREFERENCES;

-- 20. CHECK ANALYTICS
SELECT *
FROM CORE.GROUP_ANALYTICS;
