CREATE OR REPLACE TABLE CORE.GROUP_PREFERENCES (
    GROUP_ID STRING,
    USER_ID INT AUTOINCREMENT,
    BUDGET FLOAT,
    DESTINATION STRING,
    DURATION INT,
    TRAVEL_STYLE STRING,
    SHOPPING_INTEREST STRING,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE VIEW CORE.GROUP_ANALYTICS AS
SELECT
    GROUP_ID,
    COUNT(*) AS TOTAL_USERS,
    AVG(BUDGET) AS AVG_BUDGET,
    MIN(BUDGET) AS MIN_BUDGET,
    MAX(BUDGET) AS MAX_BUDGET,
    MAX(DURATION) AS MAX_DURATION,
    MIN(DURATION) AS MIN_DURATION
FROM CORE.GROUP_PREFERENCES
GROUP BY GROUP_ID;

SELECT *
FROM CORE.GROUP_ANALYTICS;

CREATE OR REPLACE PROCEDURE CORE.CLEAR_GROUP(GID STRING)
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    DELETE FROM CORE.GROUP_PREFERENCES
    WHERE GROUP_ID = :GID;

    RETURN 'Group Cleared Successfully';
END;
$$;

CALL CORE.CLEAR_GROUP('G1');

INSERT INTO CORE.GROUP_PREFERENCES (
    GROUP_ID,
    BUDGET,
    DESTINATION,
    DURATION,
    TRAVEL_STYLE,
    SHOPPING_INTEREST
)
VALUES
    ('G1', 50000, 'Goa', 3, 'Relaxed', 'Medium'),
    ('G1', 60000, 'Goa', 4, 'Adventure', 'High');

SELECT *
FROM CORE.GROUP_PREFERENCES;

SELECT *
FROM CORE.GROUP_ANALYTICS;

CALL CORE.CLEAR_GROUP('G1');

SELECT *
FROM CORE.GROUP_PREFERENCES;

CREATE OR REPLACE FILE FORMAT CORE.CSV_FORMAT
TYPE = 'CSV'
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
SKIP_HEADER = 1;

CREATE OR REPLACE STAGE CORE.PACKVOTE_STAGE
FILE_FORMAT = CORE.CSV_FORMAT;

-- COPY INTO CORE.GROUP_PREFERENCES
-- FROM @CORE.PACKVOTE_STAGE
-- FILE_FORMAT = (FORMAT_NAME = CORE.CSV_FORMAT);

SHOW STAGES LIKE 'PACKVOTE_STAGE';

SHOW FILE FORMATS LIKE 'CSV_FORMAT';

CREATE OR REPLACE FILE FORMAT CORE.CSV_FORMAT
TYPE = 'CSV'
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
SKIP_HEADER = 1;

CREATE OR REPLACE STAGE CORE.PACKVOTE_STAGE
FILE_FORMAT = CORE.CSV_FORMAT;

DESC TABLE CORE.GROUP_PREFERENCES;

SHOW STAGES;

LIST @PACKVOTE_STAGE;

SHOW TABLES LIKE 'GROUP_PREFERENCES';

SHOW FILE FORMATS;

DESC FILE FORMAT TRAVEL_CSV_FORMAT;

DELETE STAGE GROUP_STAGE;

DESC STAGE CORE.PACKVOTE_STAGE;
