CREATE OR REPLACE TABLE CORE.GROUP_PREFERENCES (
    GROUP_ID STRING,
    USER_ID INT AUTOINCREMENT,
    BUDGET FLOAT,
    DESTINATION STRING,
    DURATION INT,
    TRAVEL_STYLE STRING,
    SHOPPING_INTEREST STRING,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE VIEW CORE.GROUP_ANALYTICS AS
SELECT
    GROUP_ID,
    COUNT(*) AS TOTAL_USERS,
    AVG(BUDGET) AS AVG_BUDGET,
    MIN(BUDGET) AS MIN_BUDGET,
    MAX(BUDGET) AS MAX_BUDGET,
    MAX(DURATION) AS MAX_DURATION,
    MIN(DURATION) AS MIN_DURATION
FROM CORE.GROUP_PREFERENCES
GROUP BY GROUP_ID;

SELECT * FROM CORE.GROUP_ANALYTICS;

CREATE OR REPLACE PROCEDURE CORE.CLEAR_GROUP(GID STRING)
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    DELETE FROM CORE.GROUP_PREFERENCES 
    WHERE GROUP_ID = :GID;

    RETURN 'Group Cleared Successfully';
END;
$$;

CALL CORE.CLEAR_GROUP('G1');

--test
INSERT INTO CORE.GROUP_PREFERENCES
(GROUP_ID, BUDGET, DESTINATION, DURATION, TRAVEL_STYLE, SHOPPING_INTEREST)
VALUES
('G1', 50000, 'Goa', 3, 'Relaxed', 'Medium'),
('G1', 60000, 'Goa', 4, 'Adventure', 'High');

SELECT * FROM CORE.GROUP_PREFERENCES;

SELECT * FROM CORE.GROUP_ANALYTICS;

CALL CORE.CLEAR_GROUP('G1');

SELECT * FROM CORE.GROUP_PREFERENCES;
